name       : breeze
version    : 5.16.1
release    : 40
source     :
    - https://download.kde.org/stable/plasma/5.16.1/breeze-5.16.1.tar.xz : bf4fba98f83311365f249d706689f327380db2de61ca7bb2a8442472e0b1316e
license    :
    - GPL-2.0
    - LGPL-3.0
component  : desktop.theme
optimize   : lto
summary    : Artwork, styles and assets for the Breeze visual style for the Plasma Desktop
description: |
    Artwork, styles and assets for the Breeze visual style for the Plasma Desktop.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - frameworkintegration-devel
    - kcmutils-devel
    - kdecoration-devel
    - kguiaddons-devel
    - ki18n-devel
    - kwayland-devel
    - plasma-framework-devel
rundeps    :
    - qt5-quickcontrols
    - devel :
        - breeze-cursor-theme
        - breeze-snow-cursor-theme
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    #Remove breeze cursors as provided separately
    rm -rf $installdir/usr/share/icons
