name       : breeze
version    : 5.9.5
release    : 4
source     :
    - https://download.kde.org/stable/plasma/5.9.5/breeze-5.9.5.tar.xz : 83312b854282636bc6d10a1e579c5a13538394b76af5963f3e79b0d235053e3d
license    :
    - GPL-2.0
    - LGPL-3.0
component  : desktop.theme
summary    : Artwork, styles and assets for the Breeze visual style for the Plasma Desktop
description: |
    Artwork, styles and assets for the Breeze visual style for the Plasma Desktop.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - frameworkintegration-devel
    - kcmutils-devel
    - kconfigwidgets-devel
    - kdecoration-devel
    - kguiaddons-devel
    - ki18n-devel
    - kpackage-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    #Remove breeze cursors as provided separately
    rm -rf $installdir/usr/share/icons
    rm -rf $installdir/usr/share/wallpapers
