name       : breeze
version    : 5.21.5
release    : 79
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.5/breeze-5.21.5.tar.xz : 9774c695da7d51c45116f85358e002663a1ccc5681b04c9afc7a57e8b075980c
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - GPL-2.0-only
    - GPL-2.0-or-later
    - MIT
component  :
    - desktop.theme
    - ^breeze-cursor-theme : desktop.theme
    - ^breeze-light-cursor-theme : desktop.theme
optimize   : lto
summary    :
    - Artwork, styles and assets for the Breeze visual style for the Plasma Desktop
    - ^breeze-cursor-theme : Breeze cursor theme
    - ^breeze-light-cursor-theme : Breeze Snow cursor theme
description:
    - Artwork, styles and assets for the Breeze visual style for the Plasma Desktop
    - ^breeze-cursor-theme : Breeze cursor theme
    - ^breeze-light-cursor-theme : Breeze Snow cursor theme
patterns   :
    - ^breeze-cursor-theme :
        - /usr/share/icons/breeze_cursors
        - /usr/share/icons/default/index.theme
    - ^breeze-light-cursor-theme : /usr/share/icons/Breeze_Snow
replaces   :
    - ^breeze-light-cursor-theme : breeze-snow-cursor-theme
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - frameworkintegration-devel
    - kcmutils-devel
    - kdecoration-devel
    - kguiaddons-devel
    - ki18n-devel
    - plasma-framework-devel
rundeps    :
    - qt5-quickcontrols
    - devel :
        - breeze-cursor-theme
        - breeze-light-cursor-theme
setup      : |
    %patch -p1 -i $pkgfiles/fix-splitterproxy.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache

    # Electron-based applications will segfault if this doesn't exist. Do not remove under any circumstance.
    install -Dm00644 $pkgfiles/index.theme $installdir/usr/share/icons/default/index.theme
