name       : breeze
version    : 5.16.0
release    : 39
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.0/breeze-5.16.0.tar.xz : eb37e75b6a463648edd1b421e06531054a361af9b60e0e4fb1588a36212a4dae
license    :
    - GPL-2.0
    - LGPL-3.0
component  : desktop.theme
optimize   : lto
summary    : Artwork, styles and assets for the Breeze visual style for the Plasma Desktop
description: |
    Artwork, styles and assets for the Breeze visual style for the Plasma Desktop.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - frameworkintegration-devel
    - kcmutils-devel
    - kdecoration-devel
    - kguiaddons-devel
    - ki18n-devel
    - kwayland-devel
    - plasma-framework-devel
rundeps    :
    - qt5-quickcontrols
    - devel :
        - breeze-cursor-theme
        - breeze-snow-cursor-theme
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    #Remove breeze cursors as provided separately
    rm -rf $installdir/usr/share/icons
