name       : breeze
version    : 5.12.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.0/breeze-5.12.0.tar.xz : 7272e96d1b0c81cb8384e99a334bb3c94aed90637c9b88e00241d9e0ed8470bc
license    :
    - GPL-2.0
    - LGPL-3.0
component  : desktop.theme
optimize   : lto
summary    : Artwork, styles and assets for the Breeze visual style for the Plasma Desktop
description: |
    Artwork, styles and assets for the Breeze visual style for the Plasma Desktop.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - frameworkintegration-devel
    - kcmutils-devel
    - kconfigwidgets-devel
    - kdecoration-devel
    - kguiaddons-devel
    - ki18n-devel
    - kpackage-devel
    - kwayland-devel
    - kwindowsystem-devel
    - plasma-framework-devel
rundeps    :
    - qt5-quickcontrols
    - devel :
        - breeze-cursor-theme
        - breeze-snow-cursor-theme
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
    #Remove breeze cursors as provided separately
    rm -rf $installdir/usr/share/icons
