name       : breeze
version    : 5.10.5
release    : 8
source     :
    - https://download.kde.org/stable/plasma/5.10.5/breeze-5.10.5.tar.xz : 1ba46701e13f983b97c7e7dd01da8637a2f17ee818928064f4729895ac1dac66
license    :
    - GPL-2.0
    - LGPL-3.0
component  : desktop.theme
summary    : Artwork, styles and assets for the Breeze visual style for the Plasma Desktop
description: |
    Artwork, styles and assets for the Breeze visual style for the Plasma Desktop.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - frameworkintegration-devel
    - kcmutils-devel
    - kconfigwidgets-devel
    - kdecoration-devel
    - kguiaddons-devel
    - ki18n-devel
    - kpackage-devel
    - kwayland-devel
    - kwindowsystem-devel
    - plasma-framework-devel
rundeps    :
    - devel :
        - breeze-cursor-theme
        - breeze-snow-cursor-theme
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
    #Remove breeze cursors as provided separately
    rm -rf $installdir/usr/share/icons
