name       : breeze
version    : 5.7.4
release    : 1
source     :
    - http://download.kde.org/stable/plasma/5.7.4/breeze-5.7.4.tar.xz : 0695f02b068a72760e9b2a0802820c32fd4627c7d0af14f8b43dcc7f905d4c6a
license    :
    - GPL-2.0
    - LGPL-3.0
component  : desktop.theme
summary    : Artwork, styles and assets for the Breeze visual style for the Plasma Desktop
description: |
    Artwork, styles and assets for the Breeze visual style for the Plasma Desktop.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kdecoration-devel
    - kguiaddons-devel
    - ki18n-devel
    - kpackage-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
