name       : breeze
version    : 5.11.1
release    : 10
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.1/breeze-5.11.1.tar.xz : 970a0e9a50dfb49252cbf341e6fe3ee88c5e6870a490edd667d5e208e4c90b7b
license    :
    - GPL-2.0
    - LGPL-3.0
component  : desktop.theme
summary    : Artwork, styles and assets for the Breeze visual style for the Plasma Desktop
description: |
    Artwork, styles and assets for the Breeze visual style for the Plasma Desktop.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - frameworkintegration-devel
    - kcmutils-devel
    - kconfigwidgets-devel
    - kdecoration-devel
    - kguiaddons-devel
    - ki18n-devel
    - kpackage-devel
    - kwayland-devel
    - kwindowsystem-devel
    - plasma-framework-devel
rundeps    :
    - devel :
        - breeze-cursor-theme
        - breeze-snow-cursor-theme
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
    #Remove breeze cursors as provided separately
    rm -rf $installdir/usr/share/icons
