name       : breeze
version    : 5.14.5
release    : 34
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.5/breeze-5.14.5.tar.xz : e78e6eec31cf8fb7c6d1d823e07bebcabf978ba94772081490a38a5ac5871796
license    :
    - GPL-2.0
    - LGPL-3.0
component  : desktop.theme
optimize   : lto
summary    : Artwork, styles and assets for the Breeze visual style for the Plasma Desktop
description: |
    Artwork, styles and assets for the Breeze visual style for the Plasma Desktop.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(fftw3)
    - extra-cmake-modules
    - frameworkintegration-devel
    - kcmutils-devel
    - kconfigwidgets-devel
    - kdecoration-devel
    - kguiaddons-devel
    - ki18n-devel
    - kpackage-devel
    - kwayland-devel
    - kwindowsystem-devel
    - plasma-framework-devel
rundeps    :
    - qt5-quickcontrols
    - devel :
        - breeze-cursor-theme
        - breeze-snow-cursor-theme
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    #Remove breeze cursors as provided separately
    rm -rf $installdir/usr/share/icons
