name       : breeze
version    : 5.15.3
release    : 36
source     :
    - https://cdn.download.kde.org/stable/plasma/5.15.3/breeze-5.15.3.tar.xz : 4be0b50deb6a3b42e3c09461ebef76f0af758c400c998b627bc72931d8b3fe50
license    :
    - GPL-2.0
    - LGPL-3.0
component  : desktop.theme
optimize   : lto
summary    : Artwork, styles and assets for the Breeze visual style for the Plasma Desktop
description: |
    Artwork, styles and assets for the Breeze visual style for the Plasma Desktop.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - frameworkintegration-devel
    - kcmutils-devel
    - kdecoration-devel
    - kguiaddons-devel
    - ki18n-devel
    - kwayland-devel
    - plasma-framework-devel
rundeps    :
    - qt5-quickcontrols
    - devel :
        - breeze-cursor-theme
        - breeze-snow-cursor-theme
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    #Remove breeze cursors as provided separately
    rm -rf $installdir/usr/share/icons
