name       : breeze
version    : 5.8.4
release    : 2
source     :
    - http://download.kde.org/stable/plasma/5.8.4/breeze-5.8.4.tar.xz : dc27a3629beb6b4aa04380421110ea4f28131bea10febf25a7f11ee753deb44b
license    :
    - GPL-2.0
    - LGPL-3.0
component  : desktop.theme
summary    : Artwork, styles and assets for the Breeze visual style for the Plasma Desktop
description: |
    Artwork, styles and assets for the Breeze visual style for the Plasma Desktop.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kdecoration-devel
    - kguiaddons-devel
    - ki18n-devel
    - kpackage-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    #Remove breeze cursors as provided separately
    rm -rf $installdir/usr/share/icons
    rm -rf $installdir/usr/share/wallpapers
